[profile.default]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@ccip/=lib/ccip/",
    "@chainlink/local/=lib/chainlink-local/",
]
src = "src"
rpc_endpoints = { sepolia = "https://rpc2.sepolia.org", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/mwHkM74gwkO6kdWQKCYBRWdbDUnhZB7E", zksync = "https://sepolia.era.zksync.dev" }
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
